name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  CI:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Verify Node.js Version
        run: node -v
        
      - name: Install Dependencies
        run: npm install
        
      # Install and Configure JFrog CLI
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog
          mv jfrog /usr/local/bin/
          jfrog --version  # Verify installation

      - name: Configure JFrog CLI
        run: |
          jfrog config add my-jfrog-server \
            --artifactory-url=${{ secrets.JFROG_URL }} \
            --user=${{ secrets.JFROG_USERNAME }} \
            --password=${{ secrets.JFROG_PASSWORD }} \
            --interactive=false

      # Run JFrog Xray Security Scan
      - name: Run JFrog Xray Scan
        run: |
          jfrog xr curl -X POST /api/v1/scanArtifact \
          -H "Content-Type: application/json" \
          -d '{ "component_id": "npm://my-project" }'
        continue-on-error: true  # Prevents pipeline failure if Xray is unavailable

      - name: Run Linter
        run: npm run lint
        
      - name: Run Unit Tests
        run: npm test -- --coverage || true
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
